name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/maven.yml
      - src/**
      - pom.xml
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/maven.yml
      - src/**
      - pom.xml
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # 每六小时自动运行一次

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.15.0
      with:
        maven-version: '3.8.7'
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: 删除旧的jar包以及运行脚本
      run: sshpass -p ${{secrets.REMOTE_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_IP}} "cd /root/GitHub_Action && rm -rf ./*"

    - name: 上传jar包和启动脚本到服务器中
      run: sshpass -p ${{secrets.REMOTE_PWD}} scp -r -o StrictHostKeyChecking=no ./target/GitHub_Action-0.0.1-SNAPSHOT.jar ./run.sh root@${{secrets.REMOTE_IP}}:/root/GitHub_Action

    - name: 启动项目
      run: sshpass -p ${{secrets.REMOTE_PWD}} ssh -o StrictHostKeyChecking=no root@${{secrets.REMOTE_IP}} "cd /root/GitHub_Action && chmod +x run.sh && ./run.sh"
