name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/maven.yml
      - src/**
      - pom.xml
  pull_request:
    branches: [ "main" ]
    paths:
      - .github/workflows/maven.yml
      - src/**
      - pom.xml
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # 每六小时自动运行一次

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Maven
      uses: s4u/setup-maven-action@v1.15.0
      with:
        maven-version: '3.8.7'
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive

    - name: Deploy to server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: target/louise-0.1.7-dev.jar
        remote: /home/darcklh/qqbot/MyLouise/louise-0.1.7-dev.jar
        host: ${{ secrets.AZURE_HOST }}
        username: ${{ secrets.AZURE_USERNAME }}
        privateKey: ${{ secrets.AZURE_SSH_KEY }}
    - name: Run App
      if: always()
      uses: fifsky/ssh-action@master
      with:
        command: cd /home/darcklh/qqbot/MyLouise && ./restart.sh ./louise-0.1.7-dev.jar &
        host: ${{ secrets.AZURE_HOST }}
        user: ${{ secrets.AZURE_USERNAME }}
        key: ${{ secrets.AZURE_SSH_KEY }}
        args: "-tt"
        
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
